"""Change User model constraints

Revision ID: e9183a0be592
Revises: 5018e0786699
Create Date: 2023-12-05 16:20:09.679834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9183a0be592'
down_revision = '5018e0786699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('_password_hash',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
